### PR TITLE
Allow the user to create a new tag using `neuron--select-tag-from-query'

### PR DESCRIPTION
**Pull request by pjones**
If the user enters a tag name that does not exist `ivy-read` will
return it, but then `get-text-property` will return `nil`.  In that
case just return the user-entered text.

### CODE REVIEW

**Comment by felko** [comment]
Good idea, thank you.
I believe `neuron--select-tag-from-query` should rather take an optional `require-match` argument that controls this behavior, because in some cases (e.g. in `neuron-query-tags`) we actually want the user to select an existing tag.
Also, I was thinking maybe entering a new tag could reload the zettel cache?

**Comment by pjones** [comment]
Good ideas.  I'll update this PR.

**Comment by pjones** [comment]
@felko I added the `require-match` argument and the cache rebuild.

**Comment by felko** [comment]
Thank you!

**Pull request merged**
